#!/bin/bash
cat cat-cat | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cat-cat
cat cat-cow | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cat-cow
cat cat-dog | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cat-dog
cat cat-guinea_pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cat-guinea_pig
cat cat-horse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cat-horse
cat cat-human | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cat-human
cat cat-mouse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cat-mouse
cat cat-pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cat-pig
cat cat-rabbit | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cat-rabbit
cat cat-rta | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cat-rta
cat cat-sheep | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cat-sheep
cat cow-cow | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cow-cow
cat cow-dog | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cow-dog
cat cow-guinea_pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cow-guinea_pig
cat cow-horse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cow-horse
cat cow-human | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cow-human
cat cow-mouse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cow-mouse
cat cow-pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cow-pig
cat cow-rabbit | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cow-rabbit
cat cow-rta | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cow-rta
cat cow-sheep | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/cow-sheep
cat dog-dog | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/dog-dog
cat dog-guinea_pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/dog-guinea_pig
cat dog-horse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/dog-horse
cat dog-human | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/dog-human
cat dog-mouse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/dog-mouse
cat dog-pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/dog-pig
cat dog-rabbit | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/dog-rabbit
cat dog-rta | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/dog-rta
cat dog-sheep | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/dog-sheep
cat guinea_pig-guinea_pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/guinea_pig-guinea_pig
cat guinea_pig-horse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/guinea_pig-horse
cat guinea_pig-human | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/guinea_pig-human
cat guinea_pig-mouse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/guinea_pig-mouse
cat guinea_pig-pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/guinea_pig-pig
cat guinea_pig-rabbit | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/guinea_pig-rabbit
cat guinea_pig-rta | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/guinea_pig-rta
cat guinea_pig-sheep | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/guinea_pig-sheep
cat horse-horse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/horse-horse
cat horse-human | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/horse-human
cat horse-mouse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/horse-mouse
cat horse-pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/horse-pig
cat horse-rabbit | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/horse-rabbit
cat horse-rta | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/horse-rta
cat horse-sheep | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/horse-sheep
cat human-human | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/human-human
cat human-mouse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/human-mouse
cat human-pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/human-pig
cat human-rabbit | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/human-rabbit
cat human-rta | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/human-rta
cat human-sheep | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/human-sheep
cat mouse-mouse | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/mouse-mouse
cat mouse-pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/mouse-pig
cat mouse-rabbit | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/mouse-rabbit
cat mouse-rta | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/mouse-rta
cat mouse-sheep | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/mouse-sheep
cat pig-pig | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/pig-pig
cat pig-rabbit | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/pig-rabbit
cat pig-rta | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/pig-rta
cat pig-sheep | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/pig-sheep
cat rabbit-rabbit | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/rabbit-rabbit
cat rabbit-rta | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/rabbit-rta
cat rabbit-sheep | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/rabbit-sheep
cat rta-rta | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/rta-rta
cat rta-sheep | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/rta-sheep
cat sheep-sheep | awk '!a[$1" "$2]++{print}'  > ../Converse/uniq_simility/sheep-sheep
